// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE2iPEVzO37tl6fP6t4EmTf7GifUlmHdQ',
    appId: '1:459567867167:web:4c33e25d9171ca2f3d7c2a',
    messagingSenderId: '459567867167',
    projectId: 'orlogozarlaga-15829',
    authDomain: 'orlogozarlaga-15829.firebaseapp.com',
    storageBucket: 'orlogozarlaga-15829.firebasestorage.app',
    measurementId: 'G-8GVPJ7BJDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mxrLWTgvKBjwqWmeiUnIh5wCnBwMxa4',
    appId: '1:459567867167:android:d9ffd7e3d7dca73d3d7c2a',
    messagingSenderId: '459567867167',
    projectId: 'orlogozarlaga-15829',
    storageBucket: 'orlogozarlaga-15829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7IZtluehQdhMuIno3pAUG3loCKWwEo_U',
    appId: '1:459567867167:ios:b74f6bd4426ed2d33d7c2a',
    messagingSenderId: '459567867167',
    projectId: 'orlogozarlaga-15829',
    storageBucket: 'orlogozarlaga-15829.firebasestorage.app',
    iosBundleId: 'com.example.orlogoZarlaga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7IZtluehQdhMuIno3pAUG3loCKWwEo_U',
    appId: '1:459567867167:ios:b74f6bd4426ed2d33d7c2a',
    messagingSenderId: '459567867167',
    projectId: 'orlogozarlaga-15829',
    storageBucket: 'orlogozarlaga-15829.firebasestorage.app',
    iosBundleId: 'com.example.orlogoZarlaga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE2iPEVzO37tl6fP6t4EmTf7GifUlmHdQ',
    appId: '1:459567867167:web:5a61c518292ffa933d7c2a',
    messagingSenderId: '459567867167',
    projectId: 'orlogozarlaga-15829',
    authDomain: 'orlogozarlaga-15829.firebaseapp.com',
    storageBucket: 'orlogozarlaga-15829.firebasestorage.app',
    measurementId: 'G-JXW4SBZ6NY',
  );
}
